-- Migration 028: Daycare profile fields for receipts and invoices

ALTER TABLE daycare_settings
  ADD COLUMN IF NOT EXISTS daycare_name VARCHAR(200),
  ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(255),
  ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255),
  ADD COLUMN IF NOT EXISTS city VARCHAR(100),
  ADD COLUMN IF NOT EXISTS province VARCHAR(100),
  ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20),
  ADD COLUMN IF NOT EXISTS phone1 VARCHAR(30),
  ADD COLUMN IF NOT EXISTS phone2 VARCHAR(30),
  ADD COLUMN IF NOT EXISTS contact_name VARCHAR(200),
  ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(30),
  ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS signature_name VARCHAR(200);
