ALTER TABLE payouts
ADD COLUMN IF NOT EXISTS bonus_hours DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS bonus_rate DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS bonus_pay_current DECIMAL(10, 2) NOT NULL DEFAULT 0;
