ALTER TABLE payouts
ADD COLUMN IF NOT EXISTS regular_pay_ytd DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS sick_pay_ytd DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS vacation_pay_ytd DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS stat_pay_ytd DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS bonus_pay_ytd DECIMAL(10, 2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS retro_payment_ytd DECIMAL(10, 2) NOT NULL DEFAULT 0;
